---
# https://eengstrom.github.io/musings/generate-non-contiguous-subuid-subgid-maps-for-rootless-podman

- name: Get user infos
  getent:
    database: passwd

- name: Set subuids
  ansible.builtin.lineinfile:
    path: "/etc/subuid"
    regexp: "{{ user }}"
    line: "{{ user }}:{{ getent_passwd[user].1 | int | bitwise_shift_left(subuid_bitshift) }}:65536"
    backup: true
    create: true
    mode: 0644
    owner: root
    group: root
  loop: "{{ subid_users }}"
  loop_control:
    loop_var: "user"

- name: Set subgids
  ansible.builtin.lineinfile:
    path: "/etc/subgid"
    regexp: "{{ user }}"
    line: "{{ user }}:{{ getent_passwd[user].2 | int | bitwise_shift_left(subgid_bitshift) }}:65536"
    backup: true
    create: true
    mode: 0644
    owner: root
    group: root
  loop: "{{ subid_users }}"
  loop_control:
    loop_var: "user"
