name: Molecule

on:
  pull_request: {}

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v5
      - name: setup
        run: make setup
      - name: Molecule
        run: |
          molecule --debug test --scenario-name default
